### ISSUE TITLE
Duplicated Mob Levels

### ISSUE THREAD

**Issue by Deadmano** [Wacky-Mole/WackyEpicMMOSystem#12]
When using [BetterUI ](https://thunderstore.io/c/valheim/p/BetterUI_ForeverMaintained/BetterUI_ForeverMaintained/)with their `showEnemyHPText` option enabled, I get duplicated levels shown.
![image](https://github.com/Wacky-Mole/WackyEpicMMOSystem/assets/7104251/5a75dafb-ad5d-41f9-82c9-a4a08abb0657)

The main reason I like that option is because it shows the amount of HP the mob has, which this mod does not seem to have an option for. If you could add such an option, with star displays showing as well and perhaps a large width as per the image, that'd be amazing!

But for now I'd settle for a way to prevent the duplicated levels showing. If I remove `[@]` from this mod's `Mob Level UI String` option, then it removes both copies but I get no level indicator.

**Comment by Wacky-Mole** [comment]
Yes, it's a known issue with BetterUI. I probably wont fix.
