### ISSUE TITLE
Please Add An Option To Disable The UI Changes

### ISSUE THREAD

**Issue by Deadmano** [Wacky-Mole/WackyEpicMMOSystem#13]
I really like the original UI, and have no need for an EXP bar (immersive). Any chance you could PLEASE give us an option to disable the UI changes made to the HP/Stamina/Eitr bars etc? I'd really like to use this mod but the visuals and no way to return the original makes it a hard choice.

**Comment by Wacky-Mole** [comment]
You can manually disable all of the UI's with "none" in each of the Color configs.
