### ISSUE TITLE
[Suggestion] Change or make it possible to choose to change the magic fermenter.

### ISSUE THREAD

**Issue by Sketaful** [Wacky-Mole/WackyEpicMMOSystem#14]
Mod works perfectly so more a request,

Could you please change the magic fermenter or add a config choice to change it?   
Like it is now it's so out of place with everything else in the game that it looks horrible.   
(we hide it when we use it to not have to watch it).  

And the same for when it's done. An option to just, I don't know, look like an ordinary fermenter? 

The mod is awesome in all other ways.

**Comment by Wacky-Mole** [comment]
Haha, I love my little stupid magic fermenter. Lol.

You can do it with wackydatabase, but I'll go ahead and add a config sometime.

**Comment by Sketaful** [comment]
Lol. Well. It's a bit to colourful. The actual look with the heads and stuff wouldn't be that bad if not for the kinda shining rainbow colors. It just look so, so out of place. I think it's because I try to make things come together. I always look at mods and think on how they would fit each other. ;p

But yeah, a config for that would be appreciated. On the other hand I need something to make me put down time to learn how to change stuff like that with wacky database :)
