### ISSUE TITLE
[Request] Add UI support for riding tames

### ISSUE THREAD

**Issue by cCaptainn** [Wacky-Mole/WackyEpicMMOSystem#17]
Is it possible to add support for Tame HP and Stamina bars to MMOs hud? I'm running onto issues with my desired hud placement and the games defaults.

**Comment by Wacky-Mole** [comment]
Just move the Hud around?

**Comment by cCaptainn** [comment]
Yeah you can do that. I would also think you'd want the hud to match thematically, rather than leaving it half finished. Your choice of course.

**Comment by Wacky-Mole** [comment]
Oh, that's what you meant.  Unfortunately, it's really a lot of work to make UI. 
 It would have to be paid commission for me to even consider that.
