### ISSUE TITLE
Group XP not working properly

### ISSUE THREAD

**Issue by nigelmcdonald** [Wacky-Mole/WackyEpicMMOSystem#18]
I am running groups with group XP enabled in the Wacky config, but unfortunately it makes it so only one person gets exp from anything other than kills(which it shares correctly) the person who randomly cannot get harvesting XP can never get it, also being in a group or not does not effect getting this XP or not.

I have tried playing with the XP range which does not seem to be the issue, that only effect the person who is correctly getting XP and does not effect the person who isn't

I have also tried removing and reading my friend before creating a group and I have also tried adding them to the group without adding them as a friend but this does not have any effect

Logging out and in does not fix the issue, but it may swap who is getting the XP regardless of not grouping again. Server restart also does not fix the issue

**Comment by Wacky-Mole** [comment]
I tried it with myself in a group with another instance (Gamepass).  It worked fine.  Both player's received XP.  So unless you give me more details/logs/configs, I will close the issue.
