### ISSUE TITLE
Specializing skill for building

### ISSUE THREAD

**Issue by Onins** [Wacky-Mole/WackyEpicMMOSystem#4]
Building health is not updating properly, for example the wall is always set to 400 hp regarless if the specializing is maxed out. Also smoothbrain's building mod is not working the same way. This issue might have been occurred during a valheim update.

**Comment by Wacky-Mole** [comment]
I'll take a look at this sometime.

**Comment by Wacky-Mole** [comment]
Verified that it still works. So I am closing.
