### ISSUE TITLE
Stamina and HP bar disappear when inventory is opened.

### ISSUE THREAD

**Issue by firez2469** [Wacky-Mole/WackyEpicMMOSystem#5]
Whenever the inventory is opened, the HP bar and the stamina bar disappear and don't reappear until I log out, and then log back into a world. This issue just appeared after the last update.

**Comment by Zasig** [comment]
Can confirm. It just disappears - the bug did not occur for the last week and without any change to the game or any mod version today. If you need any logs just say which or what.

**Comment by Zasig** [comment]
@firez2469 Check if your Render Scale is not Native or 100% - i changed mine to 95% and then the bug occured. So changing it back to Native fixed it.

**Comment by Wacky-Mole** [comment]
Yeah, Native scaling should fix this.
