### ISSUE TITLE
Can't get custom mobs to drop experience

### ISSUE THREAD

**Issue by CoryGuy** [Wacky-Mole/WackyEpicMMOSystem#6]
`WackyEpicMMOSystem v1.8.96`

Trying to add custom mobs from _RenegadeVikings v1.2.4_. There aren't any clear instructions on how to add your own mobs so I copied the "MonsterDB_Default.json" and filled it in the best I could.

**Comment by Wacky-Mole** [comment]
It scans any .json in that folder so just make a RenegadeViking.json and add your mobs. Feel free to give me the json file for everyone else
