### ISSUE TITLE
Parametr LevelExperience - not sync server

### ISSUE THREAD

**Issue by Tungermax** [Wacky-Mole/WackyEpicMMOSystem#9]
The LevelExperience parameter is not synchronized with the server; if you set its value on the client side and start the game, the value will be the one I set locally.
I checked several servers on which this mod was installed and it worked everywhere.

**Comment by AltairFer2** [comment]
Exist a problem when you eat anything

**Comment by Wacky-Mole** [comment]
You are right, it is done locally, unless the command recalc is done.

**Comment by Wacky-Mole** [comment]
Fixed .1.9.15
